template: testify
template-data:
  unroll-variadic: true
filename: "{{.InterfaceName}}.go"
packages:
  go.lumeweb.com/portal-plugin-template/internal/service:
    config:
      dir: ./internal/service
    interfaces:
      ItemService: {}