// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-template/internal/db/models"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"go.lumeweb.com/queryutil"
	"gorm.io/gorm"
)

// NewMockItemService creates a new instance of MockItemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockItemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockItemService {
	mock := &MockItemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockItemService is an autogenerated mock type for the core.ItemService type
type MockItemService struct {
	mock.Mock
}

type MockItemService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockItemService) EXPECT() *MockItemService_Expecter {
	return &MockItemService_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockItemService
func (_mock *MockItemService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockItemService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockItemService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockItemService_Expecter) Config() *MockItemService_Config_Call {
	return &MockItemService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockItemService_Config_Call) Run(run func()) *MockItemService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockItemService_Config_Call) Return(manager config.Manager) *MockItemService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockItemService_Config_Call) RunAndReturn(run func() config.Manager) *MockItemService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockItemService
func (_mock *MockItemService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockItemService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockItemService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockItemService_Expecter) Context() *MockItemService_Context_Call {
	return &MockItemService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockItemService_Context_Call) Run(run func()) *MockItemService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockItemService_Context_Call) Return(context core.Context) *MockItemService_Context_Call {
	_c.Call.Return(context)
	return _c
}

func (_c *MockItemService_Context_Call) RunAndReturn(run func() core.Context) *MockItemService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// CreateItem provides a mock function for the type MockItemService
func (_mock *MockItemService) CreateItem(ctx core.Context, name string, description string) (*models.Item, error) {
	ret := _mock.Called(ctx, name, description)

	if len(ret) == 0 {
		panic("no return value specified for CreateItem")
	}

	var r0 *models.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(core.Context, string, string) (*models.Item, error)); ok {
		return returnFunc(ctx, name, description)
	}
	if returnFunc, ok := ret.Get(0).(func(core.Context, string, string) *models.Item); ok {
		r0 = returnFunc(ctx, name, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(core.Context, string, string) error); ok {
		r1 = returnFunc(ctx, name, description)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemService_CreateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateItem'
type MockItemService_CreateItem_Call struct {
	*mock.Call
}

// CreateItem is a helper method to define mock.On call
//   - ctx core.Context
//   - name string
//   - description string
func (_e *MockItemService_Expecter) CreateItem(ctx interface{}, name interface{}, description interface{}) *MockItemService_CreateItem_Call {
	return &MockItemService_CreateItem_Call{Call: _e.mock.On("CreateItem", ctx, name, description)}
}

func (_c *MockItemService_CreateItem_Call) Run(run func(ctx core.Context, name string, description string)) *MockItemService_CreateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockItemService_CreateItem_Call) Return(item *models.Item, err error) *MockItemService_CreateItem_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemService_CreateItem_Call) RunAndReturn(run func(ctx core.Context, name string, description string) (*models.Item, error)) *MockItemService_CreateItem_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockItemService
func (_mock *MockItemService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockItemService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockItemService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockItemService_Expecter) DB() *MockItemService_DB_Call {
	return &MockItemService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockItemService_DB_Call) Run(run func()) *MockItemService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockItemService_DB_Call) Return(dB *gorm.DB) *MockItemService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockItemService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockItemService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function for the type MockItemService
func (_mock *MockItemService) DeleteItem(ctx core.Context, id uint64) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(core.Context, uint64) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockItemService_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type MockItemService_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx core.Context
//   - id uint64
func (_e *MockItemService_Expecter) DeleteItem(ctx interface{}, id interface{}) *MockItemService_DeleteItem_Call {
	return &MockItemService_DeleteItem_Call{Call: _e.mock.On("DeleteItem", ctx, id)}
}

func (_c *MockItemService_DeleteItem_Call) Run(run func(ctx core.Context, id uint64)) *MockItemService_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemService_DeleteItem_Call) Return(err error) *MockItemService_DeleteItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockItemService_DeleteItem_Call) RunAndReturn(run func(ctx core.Context, id uint64) error) *MockItemService_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function for the type MockItemService
func (_mock *MockItemService) GetItem(ctx core.Context, id uint64) (*models.Item, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 *models.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(core.Context, uint64) (*models.Item, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(core.Context, uint64) *models.Item); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(core.Context, uint64) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockItemService_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type MockItemService_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx core.Context
//   - id uint64
func (_e *MockItemService_Expecter) GetItem(ctx interface{}, id interface{}) *MockItemService_GetItem_Call {
	return &MockItemService_GetItem_Call{Call: _e.mock.On("GetItem", ctx, id)}
}

func (_c *MockItemService_GetItem_Call) Run(run func(ctx core.Context, id uint64)) *MockItemService_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockItemService_GetItem_Call) Return(item *models.Item, err error) *MockItemService_GetItem_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *MockItemService_GetItem_Call) RunAndReturn(run func(ctx core.Context, id uint64) (*models.Item, error)) *MockItemService_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockItemService
func (_mock *MockItemService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockItemService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockItemService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockItemService_Expecter) ID() *MockItemService_ID_Call {
	return &MockItemService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockItemService_ID_Call) Run(run func()) *MockItemService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockItemService_ID_Call) Return(s string) *MockItemService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockItemService_ID_Call) RunAndReturn(run func() string) *MockItemService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ListItems provides a mock function for the type MockItemService
func (_mock *MockItemService) ListItems(filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]models.Item, int64, error) {
	ret := _mock.Called(filters, sorts, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListItems")
	}

	var r0 []models.Item
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) ([]models.Item, int64, error)); ok {
		return returnFunc(filters, sorts, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) []models.Item); ok {
		r0 = returnFunc(filters, sorts, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(filters, sorts, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func([]queryutil.CrudFilter, []queryutil.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(filters, sorts, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockItemService_ListItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItems'
type MockItemService_ListItems_Call struct {
	*mock.Call
}

// ListItems is a helper method to define mock.On call
//   - filters []queryutil.CrudFilter
//   - sorts []queryutil.Sort
//   - pagination queryutil.Pagination
func (_e *MockItemService_Expecter) ListItems(filters interface{}, sorts interface{}, pagination interface{}) *MockItemService_ListItems_Call {
	return &MockItemService_ListItems_Call{Call: _e.mock.On("ListItems", filters, sorts, pagination)}
}

func (_c *MockItemService_ListItems_Call) Run(run func(filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination)) *MockItemService_ListItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []queryutil.CrudFilter
		if args[0] != nil {
			arg0 = args[0].([]queryutil.CrudFilter)
		}
		var arg1 []queryutil.Sort
		if args[1] != nil {
			arg1 = args[1].([]queryutil.Sort)
		}
		var arg2 queryutil.Pagination
		if args[2] != nil {
			arg2 = args[2].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockItemService_ListItems_Call) Return(items []models.Item, n int64, err error) *MockItemService_ListItems_Call {
	_c.Call.Return(items, n, err)
	return _c
}

func (_c *MockItemService_ListItems_Call) RunAndReturn(run func(filters []queryutil.CrudFilter, sorts []queryutil.Sort, pagination queryutil.Pagination) ([]models.Item, int64, error)) *MockItemService_ListItems_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockItemService
func (_mock *MockItemService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockItemService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockItemService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockItemService_Expecter) Logger() *MockItemService_Logger_Call {
	return &MockItemService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockItemService_Logger_Call) Run(run func()) *MockItemService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockItemService_Logger_Call) Return(logger *core.Logger) *MockItemService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockItemService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockItemService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// SearchItems provides a mock function for the type MockItemService
func (_mock *MockItemService) SearchItems(ctx core.Context, query string, pagination queryutil.Pagination) ([]models.Item, int64, error) {
	ret := _mock.Called(ctx, query, pagination)

	if len(ret) == 0 {
		panic("no return value specified for SearchItems")
	}

	var r0 []models.Item
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(core.Context, string, queryutil.Pagination) ([]models.Item, int64, error)); ok {
		return returnFunc(ctx, query, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(core.Context, string, queryutil.Pagination) []models.Item); ok {
		r0 = returnFunc(ctx, query, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Item)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(core.Context, string, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, query, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(core.Context, string, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, query, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockItemService_SearchItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchItems'
type MockItemService_SearchItems_Call struct {
	*mock.Call
}

// SearchItems is a helper method to define mock.On call
//   - ctx core.Context
//   - query string
//   - pagination queryutil.Pagination
func (_e *MockItemService_Expecter) SearchItems(ctx interface{}, query interface{}, pagination interface{}) *MockItemService_SearchItems_Call {
	return &MockItemService_SearchItems_Call{Call: _e.mock.On("SearchItems", ctx, query, pagination)}
}

func (_c *MockItemService_SearchItems_Call) Run(run func(ctx core.Context, query string, pagination queryutil.Pagination)) *MockItemService_SearchItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 queryutil.Pagination
		if args[2] != nil {
			arg2 = args[2].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockItemService_SearchItems_Call) Return(items []models.Item, n int64, err error) *MockItemService_SearchItems_Call {
	_c.Call.Return(items, n, err)
	return _c
}

func (_c *MockItemService_SearchItems_Call) RunAndReturn(run func(ctx core.Context, query string, pagination queryutil.Pagination) ([]models.Item, int64, error)) *MockItemService_SearchItems_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockItemService
func (_mock *MockItemService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockItemService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockItemService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockItemService_Expecter) SetConfig(cfg interface{}) *MockItemService_SetConfig_Call {
	return &MockItemService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockItemService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockItemService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockItemService_SetConfig_Call) Return() *MockItemService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockItemService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockItemService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockItemService
func (_mock *MockItemService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockItemService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockItemService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockItemService_Expecter) SetContext(ctx interface{}) *MockItemService_SetContext_Call {
	return &MockItemService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockItemService_SetContext_Call) Run(run func(ctx core.Context)) *MockItemService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockItemService_SetContext_Call) Return() *MockItemService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockItemService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockItemService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockItemService
func (_mock *MockItemService) SetDB(db *gorm.DB) {
	_mock.Called(db)
	return
}

// MockItemService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockItemService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockItemService_Expecter) SetDB(db interface{}) *MockItemService_SetDB_Call {
	return &MockItemService_SetDB_Call{Call: _e.mock.On("SetDB", db)}
}

func (_c *MockItemService_SetDB_Call) Run(run func(db *gorm.DB)) *MockItemService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockItemService_SetDB_Call) Return() *MockItemService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockItemService_SetDB_Call) RunAndReturn(run func(db *gorm.DB)) *MockItemService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockItemService
func (_mock *MockItemService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockItemService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockItemService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockItemService_Expecter) SetLogger(logger interface{}) *MockItemService_SetLogger_Call {
	return &MockItemService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockItemService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockItemService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockItemService_SetLogger_Call) Return() *MockItemService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockItemService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockItemService_SetLogger_Call {
	_c.Run(run)
	return _c
}

// UpdateItem provides a mock function for the type MockItemService
func (_mock *MockItemService) UpdateItem(ctx core.Context, id uint64, name string, description string) error {
	ret := _mock.Called(ctx, id, name, description)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(core.Context, uint64, string, string) error); ok {
		r0 = returnFunc(ctx, id, name, description)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockItemService_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type MockItemService_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx core.Context
//   - id uint64
//   - name string
//   - description string
func (_e *MockItemService_Expecter) UpdateItem(ctx interface{}, id interface{}, name interface{}, description interface{}) *MockItemService_UpdateItem_Call {
	return &MockItemService_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, id, name, description)}
}

func (_c *MockItemService_UpdateItem_Call) Run(run func(ctx core.Context, id uint64, name string, description string)) *MockItemService_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockItemService_UpdateItem_Call) Return(err error) *MockItemService_UpdateItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockItemService_UpdateItem_Call) RunAndReturn(run func(ctx core.Context, id uint64, name string, description string) error) *MockItemService_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}
